AgendaCourtier/Controllers/BrokersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using AgendaCourtier.Models;
using System.Web.Mvc;
using System.Net;
using PagedList;
using PagedList.Mvc;

namespace AgendaCourtier.Controllers
{
    public class BrokersController : Controller
    {
        AgendaCourtierEntities db = new AgendaCourtierEntities();

        // GET: Brokers
        public ActionResult Brokers()
        {
                return View();
        }

        [HttpPost]
        public ActionResult Brokers(Brokers brokers)
        {
            if (ModelState.IsValid)
            {
                db.Brokers.Add(brokers);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Enregistré avec succès";

                return RedirectToAction("BrokersList");
            }
            return View(brokers);
        }

        public ActionResult BrokersList(string searchBy, string search, int? page)
        {
            if (searchBy == "firstname")
            {
                return View(db.Brokers.Where(model => model.firstname.Contains(search) || search == null).ToList().ToPagedList(page ?? 1, 5));
            }
            else
            {
                return View(db.Brokers.Where(model => model.lastname.Contains(search) || search == null).ToList().ToPagedList(page ?? 1, 5));
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brokers brokers = db.Brokers.Find(id);
            if (brokers == null)
            {
                return HttpNotFound();
            }
            return View(brokers);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var brokers = db.Brokers.Where(model => model.idBroker == id).First();
            //Brokers brokers = db.Brokers.Find(id);
            db.Brokers.Remove(brokers);
            db.SaveChanges();
            TempData["successMessage"] = "Supprimer";

            return RedirectToAction("BrokersList");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brokers brokers = db.Brokers.Find(id);
            if (brokers == null)
            {
                return HttpNotFound();
            }
            return View(brokers);
        }

        public ActionResult Edit(int? id)
        {

            Brokers brokers = db.Brokers.Find(id);
            if (brokers == null)
            {
                return HttpNotFound();
            }
            return View(brokers);
        }

        [HttpPost]
        public ActionResult Edit(Brokers brokers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brokers).State = EntityState.Modified;
                db.SaveChanges();
                TempData["SuccessMessage"] = "Modifications enregistrées".ToString();

                return RedirectToAction("BrokersList");
            }
            return View(brokers);
        }

        public ActionResult BrokerAppointment(int? idBroker)
        {
            return RedirectToAction("Appointments", "Appointments", new { idBroker = idBroker });
        }

        public ActionResult ABlist(int? id)
        {
            return RedirectToAction("AppointmentsList", "Appointments");
        }
    }
}

AgendaCourtier/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using AgendaCourtier.Models;
using System.Web.Mvc;
using System.Net;
using PagedList;
using PagedList.Mvc;

namespace AgendaCourtier.Controllers
{
    public class CustomersController : Controller
    {
        AgendaCourtierEntities db = new AgendaCourtierEntities();

        // GET: Customers
        public ActionResult Customers()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Customers(Customers customers)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customers);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Enregistré avec succès";

                return RedirectToAction("CustomersList");
            }
            return View(customers);
        }
        public ActionResult CustomersList(string searchBy, string search, int? page, string sortBy)
        {
            ViewBag.SortlastnameParameter = string.IsNullOrEmpty(sortBy) ? "lastname desc" : "";
            ViewBag.SortfirstnameParameter = sortBy == "firstname" ? "firstname desc" : "firstname";

            var customers = db.Customers.AsQueryable();

            if (searchBy == "firstname")
            {
                customers = customers.Where(model => model.firstname.Contains(search) || search == null);
            }
            else
            {
                customers = customers.Where(model => model.lastname.Contains(search) || search == null);
            }
            switch (sortBy)
            {
                case "lastname desc":
                    customers = customers.OrderByDescending(model => model.lastname);
                    break;
                case "firstname desc":
                    customers = customers.OrderByDescending(model => model.firstname);
                    break;
                case "firstname":
                    customers = customers.OrderBy(model => model.firstname);
                    break;
                default:
                    customers = customers.OrderBy(model => model.lastname);
                    break;
            }
            return View(customers.ToPagedList(page ?? 1, 5));
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var customers = db.Customers.Where(model => model.idCustomer == id).First();
            db.Customers.Remove(customers);
            db.SaveChanges();
            TempData["SuccessMessage"] = "Supprimer";

            var list = db.Customers.ToList();
            return RedirectToAction("CustomersList", list);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customers customers = db.Customers.Find(id);
            if (customers == null)
            {
                return HttpNotFound();
            }
            return View(customers);
        }
        public ActionResult Edit(int? id)
        {
            Customers customers = db.Customers.Find(id);
            if (customers == null)
            {
                return HttpNotFound();
            }
            return View(customers);
        }

        [HttpPost]
        public ActionResult Edit(Customers customers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customers).State = EntityState.Modified;
                db.SaveChanges();
                TempData["SuccessMessage"] = "Modifications enregistrées";

                return RedirectToAction("CustomersList");
            }
            return View(customers);
        }
    }
}

AgendaCourtier/Views/Shared/_Layout.cshtml
  <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Agenda Clients - Courtiers</title>

    <!--date picker-->
    <link href="~/Scripts/build/jquery.datetimepicker.min.css" rel="stylesheet" />
    <script src="~/Scripts/build/jquery.js"></script>
    <script src="~/Scripts/build/jquery.datetimepicker.full.js"></script>

    <!--PagedList-->
    <link href="~/Content/PagedList.css" rel="stylesheet" />

    <!--FontAwesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    @*<link href="https://fonts.googleapis.com/css2?family=EB+Garamond&display=swap" rel="stylesheet">*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />

    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    <!--Alertify-->
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />


</head>

<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            @Html.ActionLink("Agenda Client - Courtier", "Index", "Home", new { area = "" }, new { @class = "nav-link active navbar-brand text-white" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Ajout d'un courtier", "Brokers", "Brokers", new { area = "" }, new { @class = "nav-link text-white" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Ajout d'un client", "Customers", "Customers", new { area = "" }, new { @class = "nav-link text-white" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Ajout d'un RDV", "Appointments", "Appointments", new { area = "" }, new { @class = "nav-link text-white" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Listes de Courtiers", "BrokersList", "Brokers", new { area = "" }, new { @class = "nav-link text-white" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Listes des Clients", "CustomersList", "Customers", new { area = "" }, new { @class = "nav-link text-white" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; Agenda Clients - Courtiers - By Guedda Sabrine</p>
        </footer>
    </div>

    <!--Script bootstrap-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!--Sabrine ne touche pas au Jquery sinon ton alertify ne fonctionne pas/ Scripts/jquery-3.6.0.min.js-->
    @*<script src="~/Scripts/jquery-3.6.0.min.js"></script>*@
    <script src="~/Scripts/bootstrap.min.js"></script>

    <!--Alertify-->
    <script src="~/Scripts/alertify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>